
DROP TABLE IF EXISTS group_1M;
DROP TABLE IF EXISTS group_1N_2N_3N;
DROP TABLE IF EXISTS group_1N_2N;
DROP TABLE IF EXISTS group_1N;
DROP TABLE IF EXISTS group_1O;
DROP TABLE IF EXISTS group_1O_2O;
DROP TABLE IF EXISTS group_1O_2O_3O;
DROP TABLE IF EXISTS group_1X_2N_3N;
DROP TABLE IF EXISTS group_1X_2N;
DROP TABLE IF EXISTS group_1X_2M;
DROP TABLE IF EXISTS group_1X_2O;
DROP TABLE IF EXISTS group_1X_2O_3O;
	